# Generated by Django 6.0.3 on 2026-07-10 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ministries", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(db_index=True, max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("HOLY_MASS", "Holy Mass"),
                            ("SUNDAY_MASS", "Sunday Mass"),
                            ("FEAST_DAY", "Feast Day"),
                            ("RETREAT", "Retreat"),
                            ("SEMINAR", "Seminar"),
                            ("WORKSHOP", "Workshop"),
                            ("YOUTH", "Youth Event"),
                            ("CHOIR", "Choir"),
                            ("MINISTRY", "Ministry Meeting"),
                            ("CATECHISM", "Catechism"),
                            ("BAPTISM", "Baptism"),
                            ("CONFIRMATION", "Confirmation"),
                            ("MARRIAGE", "Marriage"),
                            ("FUNERAL", "Funeral"),
                            ("CHARITY", "Charity"),
                            ("GENERAL", "General"),
                        ],
                        db_index=True,
                        default="GENERAL",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("venue", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("registration_deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "banner",
                    models.ImageField(
                        blank=True, null=True, upload_to="events/banners/"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="events/thumbnails/"
                    ),
                ),
                ("capacity", models.PositiveIntegerField(default=0)),
                (
                    "registered_count",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                ("is_registration_required", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("livestream_url", models.URLField(blank=True)),
                ("contact_person", models.CharField(blank=True, max_length=150)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                (
                    "ministry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="ministries.ministry",
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organized_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ["-start_date", "-start_time"],
            },
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "attendance_status",
                    models.CharField(
                        choices=[
                            ("REGISTERED", "Registered"),
                            ("ATTENDED", "Attended"),
                            ("ABSENT", "Absent"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="REGISTERED",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="events.event",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("event", "member")},
            },
        ),
    ]
