"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

from decouple import config
import dj_database_url
import cloudinary
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file
load_dotenv()

# ─────────────────────────────────────────────
# CORE SECURITY
# ─────────────────────────────────────────────
SECRET_KEY = config('SECRET_KEY')

# FIX: default should be False, not True. Never risk DEBUG=True in production
# just because an env var was forgotten on the server.
DEBUG = config('DEBUG', default=False, cast=bool)

# FIX: ALLOWED_HOSTS was previously defined twice (env-driven, then
# immediately overwritten by a hardcoded list). Keep a single source of
# truth: hardcoded dev/ngrok hosts + anything supplied via env for prod.
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    ".ngrok-free.app",   # ngrok free tunnel subdomains
    ".ngrok-free.dev",   # ngrok free tunnel subdomains (alternate TLD)
    ".ngrok.io",         # ngrok legacy subdomains
    ".ngrok-app.io",     # ngrok app subdomains
]
ALLOWED_HOSTS += [
    h for h in config('ALLOWED_HOSTS', default='').split(',') if h
]


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.forms',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "cloudinary_storage",
    "cloudinary",
    "django_filters",
    "drf_spectacular",

    # Local Apps
    "core",
    "accounts",
    "church",
    "events",
    "ministries",
    "sacraments",
    "gallery",
    "donations",
    "prayers",
    "news",
    "contact",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Uses PostgreSQL via DATABASE_URL if available (e.g. on Render), 
# otherwise falls back seamlessly to local SQLite.
DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# ─────────────────────────────────────────────
# STATIC & MEDIA
# ─────────────────────────────────────────────

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
else:
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# (Cloudinary settings consolidated further down the file)

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ─────────────────────────────────────────────
# CORS
# ─────────────────────────────────────────────
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5174",
    "http://127.0.0.1:5174",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://st-michael-s-madende-catholic-paris-gilt.vercel.app",
    "https://st-michael-s-madende-catholic-parish.onrender.com",
]

# FIX: wildcard ngrok regex + CORS_ALLOW_CREDENTIALS=True means ANY ngrok
# tunnel (not just yours) matching these patterns could make credentialed
# requests to your API if they discovered/guessed the host. Restrict this
# to DEBUG/local development only — never ship it enabled in production.
if DEBUG:
    CORS_ALLOWED_ORIGIN_REGEXES = [
        r"^https://[\w-]+\.ngrok-free\.app$",
        r"^https://[\w-]+\.ngrok-free\.dev$",
        r"^https://[\w-]+\.ngrok\.io$",
        r"^https://[\w-]+\.ngrok-app\.io$",
    ]
else:
    CORS_ALLOWED_ORIGIN_REGEXES = []

# Required so cookies/auth headers pass through ngrok / cross-origin
CORS_ALLOW_CREDENTIALS = True


# ─────────────────────────────────────────────
# EMAIL
# ─────────────────────────────────────────────
# In development, print emails to the console instead of sending them.
# Set EMAIL_BACKEND to smtp in production and fill in the SMTP settings below.
if DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = config("EMAIL_HOST", default="smtp.gmail.com")
    EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
    EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")

DEFAULT_FROM_EMAIL = "St. Michael Madende <noreply@stmichaelmadende.org>"


# ─────────────────────────────────────────────
# DJANGO REST FRAMEWORK
# ─────────────────────────────────────────────
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_RENDERER_CLASSES": (
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ),
    "DEFAULT_PAGINATION_CLASS": "core.pagination.StandardResultsPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
    ],
}

# FIX: 6000 minutes (~100 hours / 4+ days) defeats the purpose of a
# short-lived access token — a leaked token stays valid for days. Use a
# short access-token window and lean on the refresh token for longevity.
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}

AUTH_USER_MODEL = "accounts.CustomUser"


MINISTRY_CATEGORIES = (
    ("GENERAL", "General"),
    ("LITURGICAL", "Liturgical"),
    ("YOUTH", "Youth"),
    ("CHOIR", "Choir"),
    ("CHILDREN", "Children"),
    ("MEN", "Men"),
    ("WOMEN", "Women"),
    ("FAMILY", "Family"),
    ("CHARITY", "Charity"),
    ("SMALL_COMMUNITIES", "Small Christian Communities"),
    ("EVANGELIZATION", "Evangelization"),
    ("JUSTICE_AND_PEACE", "Justice and Peace"),
    ("HEALTH", "Health"),
    ("EDUCATION", "Education"),
    ("OTHER", "Other"),
)


# ─────────────────────────────────────────────
# LOGGING
# ─────────────────────────────────────────────
# FIX: removed duplicate `import os` that appeared here in the original file.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "{levelname} {asctime} {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}


# ─────────────────────────────────────────────
# CLOUDINARY CONFIG
# ─────────────────────────────────────────────
CLOUDINARY_URL = os.getenv('CLOUDINARY_URL')

if CLOUDINARY_URL:
    cloudinary.config(cloudinary_url=CLOUDINARY_URL)
else:
    cloudinary.config(
        cloud_name=os.getenv('CLOUDINARY_CLOUD_NAME'),
        api_key=os.getenv('CLOUDINARY_API_KEY'),
        api_secret=os.getenv('CLOUDINARY_API_SECRET'),
        secure=True,
    )

# FIX: STORAGES (Django 4.2+ storage API) takes precedence over the legacy
# STATICFILES_STORAGE setting, so the old code's whitenoise compression was
# silently never applied. Whitenoise now lives correctly inside STORAGES.
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage.CompressedManifestStaticFilesStorage"
            if not DEBUG
            else "django.contrib.staticfiles.storage.StaticFilesStorage"
        ),
    },
}

# Safely compute Media URL (Cloudinary CDN)
_cloud_name = cloudinary.config().cloud_name or ""
MEDIA_URL = f"https://res.cloudinary.com/{_cloud_name}/" if _cloud_name else "/media/"

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': _cloud_name,
    'API_KEY': cloudinary.config().api_key,
    'API_SECRET': cloudinary.config().api_secret,
}


# ─────────────────────────────────────────────
# DJANGO UNFOLD CONFIG
# ─────────────────────────────────────────────
UNFOLD = {
    "SITE_TITLE": "St. Michael Madende Catholic parish",
    "SITE_HEADER": "St. Michael Madende Catholic parish",
    "SITE_SUBHEADER": "Manage your platform",

    "DARK_MODE": True,  # Enable dark mode by default

    # Optional: Add your logo (recommended)
    # "SITE_LOGO": {
    #     "light": "/static/logo-light.png",
    #     "dark": "/static/logo-dark.png",
    # },

    "SHOW_SIDEBAR": True,
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,

    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Core",
                "separator": True,
                "items": [
                    {
                        "title": "Dashboard",
                        "icon": "dashboard",
                        "link": "/admin/",
                    },
                ],
            },
        ],
    },
}


# ─────────────────────────────────────────────
# PRODUCTION HARDENING (new — only active when DEBUG is False)
# ─────────────────────────────────────────────
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # If your frontend (Vercel) or any browser-based client sends
    # cookies/CSRF tokens, list the exact origins here.
    CSRF_TRUSTED_ORIGINS = [
        "https://st-michael-s-madende-catholic-paris-gilt.vercel.app",
        "https://st-michael-s-madende-catholic-parish.onrender.com",
    ]