# Generated by Django 6.0.3 on 2026-07-10 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ministry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General"),
                            ("LITURGICAL", "Liturgical"),
                            ("YOUTH", "Youth"),
                            ("CHOIR", "Choir"),
                            ("CHILDREN", "Children"),
                            ("MEN", "Men"),
                            ("WOMEN", "Women"),
                            ("FAMILY", "Family"),
                            ("CHARITY", "Charity"),
                            ("SMALL_COMMUNITIES", "Small Christian Communities"),
                            ("EVANGELIZATION", "Evangelization"),
                            ("JUSTICE_AND_PEACE", "Justice and Peace"),
                            ("HEALTH", "Health"),
                            ("EDUCATION", "Education"),
                            ("OTHER", "Other"),
                        ],
                        default="GENERAL",
                        max_length=100,
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("mission", models.TextField(blank=True)),
                ("patron_saint", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("meeting_day", models.CharField(max_length=30)),
                ("meeting_time", models.TimeField()),
                ("meeting_location", models.CharField(max_length=200)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="ministries/logos/"
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True, null=True, upload_to="ministries/banners/"
                    ),
                ),
                ("color", models.CharField(default="#0B5ED7", max_length=20)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "assistant_leader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assistant_ministries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "leader",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="led_ministries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
