# Generated by Django 6.0.3 on 2026-07-23 11:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_album_cover_image_alter_gallerymedia_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerymedia',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
    ]
