# Generated by Django 6.0.3 on 2026-07-11 19:59

import contact.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactDepartment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        validators=[contact.validators.validate_phone_number],
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("office_hours", models.CharField(blank=True, max_length=255)),
                ("icon", models.CharField(blank=True, max_length=100)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "Contact Department",
                "verbose_name_plural": "Contact Departments",
                "ordering": ("display_order", "name"),
                "indexes": [
                    models.Index(fields=["slug"], name="contact_con_slug_1bd8b0_idx"),
                    models.Index(
                        fields=["is_active"], name="contact_con_is_acti_8552f8_idx"
                    ),
                    models.Index(
                        fields=["display_order"], name="contact_con_display_8a7975_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "question",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("slug", models.SlugField(blank=True, max_length=260, unique=True)),
                (
                    "answer",
                    models.TextField(
                        validators=[django.core.validators.MinLengthValidator(10)]
                    ),
                ),
                (
                    "category",
                    models.CharField(db_index=True, default="General", max_length=100),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("is_published", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ("display_order", "question"),
                "indexes": [
                    models.Index(
                        fields=["category"], name="contact_faq_categor_b7f191_idx"
                    ),
                    models.Index(
                        fields=["is_featured"], name="contact_faq_is_feat_9ce315_idx"
                    ),
                    models.Index(
                        fields=["is_published"], name="contact_faq_is_publ_3a279e_idx"
                    ),
                    models.Index(
                        fields=["display_order"], name="contact_faq_display_71e21a_idx"
                    ),
                    models.Index(fields=["slug"], name="contact_faq_slug_3c664e_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        db_index=True, editable=False, max_length=20, unique=True
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        max_length=254,
                        validators=[contact.validators.validate_contact_email],
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        validators=[contact.validators.validate_phone_number],
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        max_length=255,
                        validators=[
                            contact.validators.validate_subject,
                            django.core.validators.MinLengthValidator(5),
                        ],
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        validators=[
                            contact.validators.validate_message,
                            django.core.validators.MinLengthValidator(10),
                            django.core.validators.MaxLengthValidator(5000),
                        ]
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="contact/attachments/%Y/%m/",
                        validators=[contact.validators.validate_attachment],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("IN_PROGRESS", "In Progress"),
                            ("RESPONDED", "Responded"),
                            ("CLOSED", "Closed"),
                            ("SPAM", "Spam"),
                        ],
                        db_index=True,
                        default="NEW",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("NORMAL", "Normal"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        db_index=True,
                        default="NORMAL",
                        max_length=20,
                    ),
                ),
                ("response", models.TextField(blank=True)),
                ("internal_notes", models.TextField(blank=True)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("is_spam", models.BooleanField(db_index=True, default=False)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_contact_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="contact.contactdepartment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["reference"], name="contact_con_referen_d15c56_idx"
                    ),
                    models.Index(fields=["email"], name="contact_con_email_233940_idx"),
                    models.Index(
                        fields=["status"], name="contact_con_status_fa3e24_idx"
                    ),
                    models.Index(
                        fields=["priority"], name="contact_con_priorit_d0a8e9_idx"
                    ),
                    models.Index(
                        fields=["department"], name="contact_con_departm_f96875_idx"
                    ),
                    models.Index(
                        fields=["is_read"], name="contact_con_is_read_9a011e_idx"
                    ),
                    models.Index(
                        fields=["is_spam"], name="contact_con_is_spam_8ef3b9_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="contact_con_created_fddb83_idx"
                    ),
                ],
            },
        ),
    ]
