# Generated by Django 6.0.3 on 2026-07-22 12:30

import cloudinary.models
import contact.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='attachment',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[contact.validators.validate_attachment], verbose_name='attachment'),
        ),
    ]
