# Generated by Django 6.0.3 on 2026-07-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.TextField()),
                ("background_image", models.ImageField(upload_to="church/hero/")),
                ("primary_button_text", models.CharField(max_length=100)),
                ("primary_button_link", models.CharField(max_length=200)),
                ("secondary_button_text", models.CharField(max_length=100)),
                ("secondary_button_link", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Leadership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("position", models.CharField(max_length=100)),
                ("photo", models.ImageField(upload_to="church/leadership/")),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("message", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="MassSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                            ("Sunday", "Sunday"),
                        ],
                        max_length=20,
                    ),
                ),
                ("service_name", models.CharField(max_length=100)),
                ("language", models.CharField(max_length=50)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("notes", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ParishInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parish_name", models.CharField(max_length=200)),
                ("motto", models.CharField(blank=True, max_length=255)),
                ("history", models.TextField()),
                ("mission", models.TextField()),
                ("vision", models.TextField()),
                ("address", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=30)),
                ("alternative_phone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("website", models.URLField(blank=True)),
                ("facebook", models.URLField(blank=True)),
                ("youtube", models.URLField(blank=True)),
                ("instagram", models.URLField(blank=True)),
                ("twitter", models.URLField(blank=True)),
                ("logo", models.ImageField(upload_to="church/logo/")),
                ("about_image", models.ImageField(upload_to="church/about/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Parish Information",
                "verbose_name_plural": "Parish Information",
            },
        ),
        migrations.CreateModel(
            name="Saint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("feast_day", models.DateField()),
                ("image", models.ImageField(upload_to="church/saints/")),
                ("quote", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Statistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("value", models.PositiveIntegerField()),
                ("icon", models.CharField(max_length=100)),
                ("display_order", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
