# Generated by Django 6.0.3 on 2026-07-22 12:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='background_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='background_image'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='parishinformation',
            name='about_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='about_image'),
        ),
        migrations.AlterField(
            model_name='parishinformation',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='saint',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
