# Generated by Django 6.0.3 on 2026-07-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacraments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sacrament',
            name='sacrament_type',
            field=models.CharField(choices=[('BAPTISM', 'Baptism'), ('CONFIRMATION', 'Confirmation'), ('EUCHARIST', 'Holy Eucharist'), ('RECONCILIATION', 'Reconciliation (Confession)'), ('ANOINTING_OF_SICK', 'Anointing of the Sick'), ('HOLY_ORDERS', 'Holy Orders'), ('MATRIMONY', 'Matrimony (Marriage)')], default='BAPTISM', help_text='Select one of the seven Catholic sacraments.', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sacrament',
            name='name',
            field=models.CharField(blank=True, help_text='Human-readable name. Auto-filled from the sacrament type if left blank.', max_length=100, unique=True),
        ),
    ]
