# Generated by Django 6.0.3 on 2026-07-22 12:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sacraments', '0002_add_sacrament_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sacrament',
            name='banner',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='banner'),
        ),
    ]
